### ISSUE TITLE
Inverting matchers doesn't affect error message

### ISSUE THREAD

**Issue by IanGrainger** [testing-library/jasmine-dom#3]
- `jasmine-dom` version: 0.0.0-semantic

### Relevant code or config:

```js
expect(screen.getByText('Yes')).not.toBeChecked();
```

### What you did:

Inverted a `toBeChecked` match - which failed.

### What happened:

`Error: FAILED Expected the element input type="radio" to be checked and it isn't checked.`

### What should have happened:

Message should either be:
`Error: FAILED Expected the element input type="radio" not to be checked and it is.`
Or:
`Error: FAILED Expected the element input type="radio" checked value to match false but it was true`

**Comment by brrianalexis** [comment]
Hmm. I had a look at both the tests and the app where I use the library and couldn't reproduce the issue.

Can you share the HTML or a repro?

**Comment by IanGrainger** [comment]
I have no idea why this didn't work. Maybe I was just stupid? 😆 
`expect(screen.getByLabelText('Checkbox is here!')).not.toBeChecked();`
gave
`Error: FAILED Expected the element input type="checkbox" not to be checked and it is checked.`. Which is perfect 👍
