### ISSUE TITLE
Vulnerabilities

### ISSUE THREAD

**Issue by IanGrainger** [testing-library/jasmine-dom#4]
Hi, sorry about this, but I can't use my forked version of your library because it has 3 vulnerabilities and I can't seem to fix them?

```
found 3 vulnerabilities (2 moderate, 1 high) in 1464 scanned packages
  3 vulnerabilities require manual review. See the full report for details.

C:\src\jasmine-dom>npm audit fix
up to date in 8.942s

95 packages are looking for funding
  run `npm fund` for details

fixed 0 of 3 vulnerabilities in 1464 scanned packages
  3 vulnerabilities required manual review and could not be updated
```

I've tried updating `kcd-scripts` but it didn't make any difference?

**Comment by brrianalexis** [comment]
Hi!

I had a look at `kcd-scripts` and the vulnerabilities come from [rollup-plugin-node-builtins](https://github.com/calvinmetcalf/rollup-plugin-node-builtins) which seems to be abandoned.

Since `kcd-scipts` is a devDependency, I guess you shouldn't have an issue using your fork on a project? 🤔
