### ISSUE TITLE
Remove type defintions

### ISSUE THREAD

**Issue by oriSomething** [testing-library/jasmine-dom#76]
We have currently `@types/testing-library__jasmine-dom` installed which make problematic upgrade type definitions. Since we want definitions of a version to yet to exist which means wrong definitions. There are 2 options:
1. Remove definitions package
2. Contain the actual TS definitions

I recommend the first option

**Comment by brrianalexis** [comment]
Agreed. If you're willing to make a PR to remove the package, go ahead. Thank you!

**Comment by oriSomething** [comment]
Also, any reason for `@babel/runtime` being a dependecy?

**Comment by oriSomething** [comment]
PR: https://github.com/testing-library/jasmine-dom/pull/77

**Comment by brrianalexis** [comment]
> Also, any reason for `@babel/runtime` being a dependecy?

Apparently, no reason. You can add a new PR to get rid of it too
